# Numpy

NumPy es una libreria para computación cientifica en Python. Provee soporte para arrays y matrices además de una colección de funciones matematicas para trabajar con esas estructuras de datos.

In [2]:
!pip install numpy # instalamos numpy

#La otra manera es utilizar requirements.txt

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [5]:
import numpy as np  #generalmente se usa np como alias de numpy

##creamos un array usando numpy
##creamos un array de una dimension

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1, 5)) #lo redimensionamos a una fila y 5 columnas

#no permitiria poner menos columnas porque ya debe tener al menos 5

array([[1, 2, 3, 4, 5]])

In [11]:
#Arreglo de dimension 2
arr2=np.array([[1,2,3,4,5], [2,3,4,5,6]])
arr2.shape
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [13]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))  #crea unos una matriz de 3X4 con 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
## matriz identidad de cierto tamaño
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
##Atributos de Numpy

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape: ", arr.shape)  #te devuelve la dimension
print("Numero de dimensiones: ", arr.ndim) #te dice cuantas dimensiones tiene
print("Cantidad de elementos presentes: ", arr.size)
print("Data type:", arr.dtype) #te dice el tipo de datos
print("Tamaño en bytes", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Numero de dimensiones:  2
Cantidad de elementos presentes:  6
Data type: int64
Tamaño en bytes 8


In [23]:
## Operaciones sobre vectores

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("suma de vectores:", arr1 + arr2)

#Resta de vectores

print("resta de vectores:", arr1 - arr2)

#Multiplicacion 

print("multiplicacion de vectores:", arr1 * arr2)

#Division

print("division de vectores:", arr1 / arr2)

suma de vectores: [11 22 33 44 55]
resta de vectores: [ -9 -18 -27 -36 -45]
multiplicacion de vectores: [ 10  40  90 160 250]
division de vectores: [0.1 0.1 0.1 0.1 0.1]


In [24]:
#Funciones universales, que se aplican a todo el array

arr = np.array([2,3,4,5,6])

#Raiz cuadrada

print(np.sqrt(arr))

#Exponencial

print(np.exp(arr))

#seno 

print(np.sin(arr))

#logaritmo natural

print(np.log(arr))




[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [28]:
#Operaciones de slicing e indexado

arr = np.array([[1,2,3,4], [5,6,7,8], [10,11,12,13]])
print("Array: \n", arr)

arr[0][0]

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]]


1

In [32]:
arr[1:, 2:] #obtener una submatriz

array([[ 7,  8],
       [12, 13]])

In [36]:
#Modificar elementos del arreglo

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [ 10  11  12  13]]


In [39]:
arr[1:] = 100  #Reemplaza todos los elementos de la fila 1 para abajo con 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [41]:
## Normalizacion 

#Transformar los datos para que tengan una media de 0 y una desviacion de 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Datos normalizados ",normalized_data)


Datos normalizados  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
#Calculo de valores estadisticos

data = np.array([1,2,3,4,5,6,7,8,9,10])

mean = np.mean(data)

median = np.median(data)

std_dev = np.std(data)

variance = np.var(data)

In [49]:
#Operaciones logicas

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5  #nos va a decir cuantos datos son mas grandes que 5

data[data > 5]  #Nos devuelve los datos segun si son o no mayores que 5



array([ 6,  7,  8,  9, 10])